version: "3.8"

services:
  p2p-client:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run build
    container_name: "p2p-client_c"
    volumes:
      - ./dist:/client/dist

