version: "3.8"

services:
  satoshi-client:
    image: "node:20"
    build:
      dockerfile: Dockerfile
    command: npm run build
    container_name: "p2p-client_c"
    #    network_mode: host
    # environment:
    #   - VITE_SECRET_KEY=${SECRET_KEY}
    #   - VITE_BASE=${API_BASE}
    volumes:
      - ./dist:/client/dist
