name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Docker Compose Configuration
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./client/docker-compose.yml
          target: ~/client/docker-compose.yml

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            echo "Switching to project directory..."
            cd ~/client/

            echo "Checking directory contents:"
            ls -al

            echo "Stopping old containers..."
            docker-compose down || true
            echo "Stopping any leftover containers..."
            docker ps -q | xargs -r docker stop || true

            echo "Pulling latest images..."
            docker-compose pull

            echo "Building new containers..."
            docker-compose build --no-cache

            echo "Starting new containers..."
            docker-compose up -d

            echo "Cleaning up unused Docker images..."
            docker image prune -f

      - name: Cleanup SSH Keys
        if: always()
        run: rm -rf ~/.ssh
