name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer files to server
        run: |
          rsync -avz --exclude=".git" --exclude=".github" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/client/

      - name: Deploy on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          set -e
          echo "Switching to project directory..."
          cd ~/client/
          
          echo "Stopping old containers..."
          docker-compose down || true
          echo "Stopping any leftover containers..."
          docker ps -q | xargs -r docker stop || true
          echo "Pulling latest images..."
          docker-compose pull

          echo "Building new containers..."
          docker-compose build --no-cache

          echo "Starting new containers..."
          docker-compose up -d
          
          echo "Cleaning up unused Docker images..."
          docker image prune -f
          EOF

      - name: Cleanup SSH keys
        if: always()
        run: rm -rf ~/.ssh
